### ISSUE TITLE
False negative

### ISSUE THREAD

**Issue by Hipapheralkus** [SecurityRiskAdvisors/Burp-Load-Balancer-Cookie-Scanner#1]
Hi, nice extension:)
I noticed that in some cases, it doesn't see the cookies for BigIP. For example DY2015dddddddddd=rd5o00000000000000000000ffffc0000201o80 or similar. It is described on https://support.f5.com/csp/article/K6917 and properly parsed here https://github.com/drwetter/F5-BIGIP-Decoder/blob/master/f5_bigip_decoder.sh - is there any chance you could implement the enhancement?:)
thanks

**Comment by dan-sra** [comment]
Just added!  Let me know if you have any problems.

**Comment by Hipapheralkus** [comment]
it works, thank you:)
A very small thing I noticed is that after the IPv4 address is parsed, I can see it as ddd.ddd.ddd.ddd%1 (where d is a digit) so the '%1' is a bit unexpected at the end, but that's a very small cosmetic issue:)

**Comment by dan-sra** [comment]
According to the link you sent, https://support.f5.com/csp/article/K6917#ipv4rd, F5 uses the IP%d format to indicate the route domain ID for IPv4 members in non-default domains.
